### ISSUE TITLE
Docker image reponse times slowdown

### ISSUE THREAD

**Issue by mwullink** [berthubert/bagconv#16]
When sending multiple requests (parallel) the response times from the docker container increase significantly, it can takes 10secs or more to get a response

**Comment by berthubert** [comment]
working on it!

**Comment by berthubert** [comment]
Should be fixed in 4af8f6a3b32eec529cbd9f7d20b78a4332274f58 can you check?

**Comment by mwullink** [comment]
trying it using a 2000ms timeout and still getting timeouts.
not sure what a reasonable timeout.value should be, any advice?
